version: '3'
services:
  # Бэкенд сервис с Django и PostgreSQL
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  # Сервис базы данных PostgreSQL
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  # Фронтенд сервис с React
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
